package org.fourstack.infomanagement.payload;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.fourstack.infomanagement.codetype.CustErrCodesAndMsgs;
import org.springframework.http.HttpStatus;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Class <b><i>ErrorResponse</i></b> is used to handle the ErrorResponses
 * generated by the Application Exceptions.
 * 
 * @author Manjunath_HM
 *
 */
/*
 * Class ErrorResponse is made Entity class to store the exceptions raised by
 * the application.
 */
@Entity
@Table(name = "error_responses")
public class ErrorResponse implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1194886948518745808L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@Column(name = "custom_error_code")
	@JsonProperty("custom_err_code")
	private CustErrCodesAndMsgs customErrorCode;

	@Column(name = "custom_error_message")
	@JsonProperty("custom_err_msg")
	private CustErrCodesAndMsgs customErrorMsg;

	@Column(name = "custom_error_description", columnDefinition = "TEXT")
	@JsonProperty("custom_err_desc")
	private String customErrorDescription;

	@Column(name = "errorcode")
	@JsonProperty("error_code")
	private int errorCode;

	@Column(name = "error_message", columnDefinition = "TEXT")
	@JsonProperty("error_msg")
	private String errorMsg;

	@Column(name = "http_status")
	@JsonProperty("http_status")
	private HttpStatus status;

	@Column(name = "uri_details")
	@JsonProperty("uri_details")
	private String urlDetails;

	@Column(name = "error_timestamp")
	@JsonProperty("timestamp")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm:ss.SSS")
	private LocalDateTime timeStamp;

	/**
	 * No Argument Constructor
	 */
	public ErrorResponse() {
	}

	/**
	 * Parameterized Constructor to initialize the ErrorResponse Object
	 * 
	 * @param customErrorCode        Custom Error Code related to the application
	 * @param customErrorMsg         Custom Error Message related to application
	 * @param customErrorDescription Custom Error Description related to the
	 *                               application
	 * @param errorCode              ErrorCode for the Response
	 * @param errorMsg               Error Message for the Response
	 * @param status                 HttpStatus for the Response
	 * @param urlDetails             URI for which ErrorResponse Generated
	 * @param timeStamp              TimeStamp to track the ErrorResponse
	 */
	public ErrorResponse(CustErrCodesAndMsgs customErrorCode, CustErrCodesAndMsgs customErrorMsg,
			String customErrorDescription, int errorCode, String errorMsg, HttpStatus status, String urlDetails,
			LocalDateTime timeStamp) {
		this.customErrorCode = customErrorCode;
		this.customErrorMsg = customErrorMsg;
		this.customErrorDescription = customErrorDescription;
		this.errorCode = errorCode;
		this.errorMsg = errorMsg;
		this.status = status;
		this.urlDetails = urlDetails;
		this.timeStamp = timeStamp;
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public CustErrCodesAndMsgs getCustomErrorCode() {
		return customErrorCode;
	}

	public void setCustomErrorCode(CustErrCodesAndMsgs customErrorCode) {
		this.customErrorCode = customErrorCode;
	}

	public CustErrCodesAndMsgs getCustomErrorMsg() {
		return customErrorMsg;
	}

	public void setCustomErrorMsg(CustErrCodesAndMsgs customErrorMsg) {
		this.customErrorMsg = customErrorMsg;
	}

	public String getCustomErrorDescription() {
		return customErrorDescription;
	}

	public void setCustomErrorDescription(String customErrorDescription) {
		this.customErrorDescription = customErrorDescription;
	}

	public int getErrorCode() {
		return errorCode;
	}

	public void setErrorCode(int errorCode) {
		this.errorCode = errorCode;
	}

	public String getErrorMsg() {
		return errorMsg;
	}

	public void setErrorMsg(String errorMsg) {
		this.errorMsg = errorMsg;
	}

	public HttpStatus getStatus() {
		return status;
	}

	public void setStatus(HttpStatus status) {
		this.status = status;
	}

	public String getUrlDetails() {
		return urlDetails;
	}

	public void setUrlDetails(String urlDetails) {
		this.urlDetails = urlDetails;
	}

	public LocalDateTime getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(LocalDateTime timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Override
	public String toString() {
		return "ErrorResponse [customErrorCode=" + customErrorCode + ", customErrorMsg=" + customErrorMsg
				+ ", customErrorDescription=" + customErrorDescription + ", errorCode=" + errorCode + ", errorMsg="
				+ errorMsg + ", status=" + status + ", urlDetails=" + urlDetails + ", timeStamp=" + timeStamp + "]";
	}
}
